
package com.login;
import java.awt.Color;
import javax.swing.*;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.io.File;
import java.util.Scanner;



/**
 *
 * @author JGal94
 */
public class Login extends javax.swing.JFrame {
    
    private File myDoc;
    private Scanner sCan;
    private secondScreen second;
    
    int xm, ym = 0;
    
    public Login() {
        String direccionProyecto = System.getProperty("user.dir");
        String add = "\\logs.txt";
        System.out.println(direccionProyecto);
        String dircorrect = direccionProyecto.replace("/","\\");
        dircorrect = dircorrect+add;
        
        
        
        second = new secondScreen();
        
         //myDoc = new File ("C:\\Users\\juanf\\OneDrive\\Escritorio\\logs.txt");
         myDoc = new File (dircorrect);
         System.out.println(dircorrect);
         try{
         sCan = new Scanner(myDoc);
         }catch(FileNotFoundException e){
             e.printStackTrace();
         }
        
        initComponents();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        contmov = new javax.swing.JPanel();
        pokebola = new javax.swing.JLabel();
        contregister = new javax.swing.JPanel();
        contlogin = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        loginlogo = new javax.swing.JLabel();
        contx = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        userlabe = new javax.swing.JLabel();
        usersep = new javax.swing.JSeparator();
        usercamp = new javax.swing.JTextField();
        passlabe = new javax.swing.JLabel();
        passsep = new javax.swing.JSeparator();
        passcamp = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contmov.setOpaque(false);
        contmov.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                contmovMouseDragged(evt);
            }
        });
        contmov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contmovMousePressed(evt);
            }
        });

        javax.swing.GroupLayout contmovLayout = new javax.swing.GroupLayout(contmov);
        contmov.setLayout(contmovLayout);
        contmovLayout.setHorizontalGroup(
            contmovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        contmovLayout.setVerticalGroup(
            contmovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        background.add(contmov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        pokebola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/pokebola.png"))); // NOI18N
        background.add(pokebola, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 390, 470));

        contregister.setBackground(new java.awt.Color(255, 255, 255));
        contregister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contlogin.setBackground(new java.awt.Color(51, 51, 51));

        login.setBackground(new java.awt.Color(204, 204, 204));
        login.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        login.setForeground(new java.awt.Color(204, 204, 204));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("LOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contloginLayout = new javax.swing.GroupLayout(contlogin);
        contlogin.setLayout(contloginLayout);
        contloginLayout.setHorizontalGroup(
            contloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contloginLayout.setVerticalGroup(
            contloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contloginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contregister.add(contlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, 50));

        loginlogo.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        loginlogo.setForeground(new java.awt.Color(51, 51, 51));
        loginlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/campooke (2).png"))); // NOI18N
        loginlogo.setText("Login");
        contregister.add(loginlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, 50));

        contx.setBackground(new java.awt.Color(255, 0, 0));
        contx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contxMouseExited(evt);
            }
        });

        x.setBackground(new Color(255,0,0));
        x.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        x.setForeground(new java.awt.Color(204, 204, 204));
        x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        x.setText("X");
        x.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contxLayout = new javax.swing.GroupLayout(contx);
        contx.setLayout(contxLayout);
        contxLayout.setHorizontalGroup(
            contxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contxLayout.setVerticalGroup(
            contxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contregister.add(contx, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        userlabe.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        userlabe.setForeground(new java.awt.Color(51, 51, 51));
        userlabe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userlabe.setText("User");
        contregister.add(userlabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 50));

        usersep.setForeground(new java.awt.Color(51, 51, 51));
        contregister.add(usersep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 10));

        usercamp.setBackground(new java.awt.Color(255, 255, 255));
        usercamp.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usercamp.setForeground(new java.awt.Color(204, 204, 204));
        usercamp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usercamp.setText("Enter your username");
        usercamp.setBorder(null);
        usercamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usercampMouseClicked(evt);
            }
        });
        usercamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usercampActionPerformed(evt);
            }
        });
        contregister.add(usercamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 20));

        passlabe.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        passlabe.setForeground(new java.awt.Color(51, 51, 51));
        passlabe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passlabe.setText("Password");
        contregister.add(passlabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 50));

        passsep.setForeground(new java.awt.Color(51, 51, 51));
        contregister.add(passsep, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 310, 10));

        passcamp.setBackground(new java.awt.Color(255, 255, 255));
        passcamp.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        passcamp.setText("password");
        passcamp.setBorder(null);
        passcamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passcampMouseClicked(evt);
            }
        });
        passcamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passcampActionPerformed(evt);
            }
        });
        contregister.add(passcamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 20));

        background.add(contregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 350, 340));

        fondo.setBackground(new java.awt.Color(153, 153, 153));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/pokemonfont.jpg"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usercampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usercampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usercampActionPerformed

    private void passcampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passcampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passcampActionPerformed

    private void xMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseClicked
        // TODO add your handling code here:
        
        
        System.exit(0);
        
    }//GEN-LAST:event_xMouseClicked

    private void contmovMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contmovMousePressed
        // TODO add your handling code here:
        xm = evt.getX();
        ym = evt.getY();
    }//GEN-LAST:event_contmovMousePressed

    private void contmovMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contmovMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xm,y - ym);
    }//GEN-LAST:event_contmovMouseDragged

    private void xMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseEntered
        // TODO add your handling code here:
        contx.setBackground(new Color(240,102,102));
        
        x.setForeground(Color.WHITE);
    }//GEN-LAST:event_xMouseEntered

    private void xMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xMouseExited
        // TODO add your handling code here:
        contx.setBackground(Color.RED);
        x.setForeground(Color.GRAY);
    }//GEN-LAST:event_xMouseExited

    private void contxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contxMouseEntered
   
    }//GEN-LAST:event_contxMouseEntered

    private void contxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contxMouseExited

    }//GEN-LAST:event_contxMouseExited

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        // TODO add your handling code here:
        login.setForeground(Color.WHITE);
        contlogin.setBackground(new Color(78,78,78));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        // TODO add your handling code here:
        login.setForeground(Color.GRAY);
        contlogin.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_loginMouseExited

    private void usercampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usercampMouseClicked
        // TODO add your handling code here:
        usercamp.setText("");
        usercamp.setForeground(Color.BLACK);
        if(String.valueOf(passcamp.getPassword()).isEmpty()){
        passcamp.setText("password");
        passcamp.setForeground(Color.GRAY);
        
        }
    }//GEN-LAST:event_usercampMouseClicked

    private void passcampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passcampMouseClicked
        // TODO add your handling code here:
        if(usercamp.getText().equals("")){
        usercamp.setText("Enter your username");
        usercamp.setForeground(Color.GRAY);
        }
        passcamp.setForeground(Color.BLACK);
        passcamp.setText("");
        
    }//GEN-LAST:event_passcampMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        
        if(String.valueOf(passcamp.getPassword()).isEmpty() || usercamp.getText().equals("") || String.valueOf(passcamp.getPassword()).equals("password")||usercamp.getText().equals("Enter your username")){
            JOptionPane.showMessageDialog(null,"Invalid user or password");
        }else{
        JOptionPane.showMessageDialog(null, "User: "+ usercamp.getText() + "\n"+"Password: "+ String.valueOf(passcamp.getPassword()));
        }
        String usercon = usercamp.getText() + " " + String.valueOf(passcamp.getPassword());
        boolean userf = false;
        
        String lin ="";
        while (sCan.hasNextLine()){
            lin = sCan.nextLine();
            if(usercon.equals(lin)){
                userf = true;
                break; 
            }
        }
        if(userf == true){
            JOptionPane.showMessageDialog(null,"Accessed");
             second.setVisible(true);
             second.secondScreen(usercamp.getText());
            
            this.setVisible(false);
            
        }else{
            JOptionPane.showMessageDialog(null,"ACCESS DENIED");
        }
        
        
        
        
        
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel contlogin;
    private javax.swing.JPanel contmov;
    private javax.swing.JPanel contregister;
    private javax.swing.JPanel contx;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel login;
    private javax.swing.JLabel loginlogo;
    private javax.swing.JPasswordField passcamp;
    private javax.swing.JLabel passlabe;
    private javax.swing.JSeparator passsep;
    private javax.swing.JLabel pokebola;
    private javax.swing.JTextField usercamp;
    private javax.swing.JLabel userlabe;
    private javax.swing.JSeparator usersep;
    private javax.swing.JLabel x;
    // End of variables declaration//GEN-END:variables
}
